# Generated by Django 4.2.2 on 2023-07-26 17:13

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='لطفا بیشتر از 250 حرف ننویسید', max_length=250, validators=[django.core.validators.MaxLengthValidator(250, 'لطفا بین 1 تا 250 حرف بنویسید')], verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(help_text='لطفا بیشتر از 35 حرف ننویسید', max_length=35, unique=True, validators=[django.core.validators.MaxLengthValidator(35, 'لطفا بین 1 تا 35 حرف بنویسید')], verbose_name='آدرس مقاله')),
                ('description', ckeditor.fields.RichTextField(help_text='محتوایی برای مقاله خود بنویسید', verbose_name='محتوای مقاله')),
                ('thumbnail', models.ImageField(help_text='برای مقاله تصویری انتخاب کنید', upload_to='images', verbose_name='تصویر مقاله')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, help_text='فرمت صحیح تاریخ YYYY-MM-DD', verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده'), ('i', 'در حال بررسی'), ('b', ' برگشت داده شده')], help_text='وضعیت مقاله را انتخاب کنید', max_length=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-publish'],
            },
        ),
    ]
