# Generated by Django 4.2.2 on 2023-07-26 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='لطفا بیشتر از 35 حرف ننویسید', max_length=35, unique=True, validators=[django.core.validators.MaxLengthValidator(35, 'لطفا بین 1 تا 35 حرف بنویسید')], verbose_name='آدرس مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(help_text='برای مقاله تصویری انتخاب کنید', upload_to='images_blog', verbose_name='تصویر مقاله'),
        ),
    ]
