# Generated by Django 4.2.2 on 2023-07-27 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_slug_alter_article_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='از 1 تا 200 حرف بنویسید', max_length=200, validators=[django.core.validators.MaxLengthValidator(200, 'لطفا بین 1 تا 200 حرف بنوسید')], verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, help_text='از 1 تا 30 حرف بنویسید', max_length=30, unique=True, validators=[django.core.validators.MaxLengthValidator(30, 'لطفا بین 1 تا 30 حرف بنوسید')], verbose_name='آدرس دسته بندی')),
                ('status', models.BooleanField(default=True, help_text='آیا نمایش داده شود ؟', verbose_name='نمایش دادن')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('position', models.IntegerField(default=1000, unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(1000000000)], verbose_name='موقعیت')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['created'],
            },
        ),
    ]
