# Generated by Django 4.2.2 on 2023-07-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(help_text='کنترل یا فرمان را در مک نگه دارید تا بیش از یک مورد انتخاب شود|', related_name='articles', to='blog.category', verbose_name='دسته بندی'),
        ),
    ]
