# Generated by Django 4.2.2 on 2023-08-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_options_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده')], help_text='وضعیت مقاله را انتخاب کنید', max_length=1, verbose_name='وضعیت'),
        ),
    ]
