# Generated by Django 4.2.2 on 2023-08-08 12:09

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, help_text='فرمت صحیح تاریخ YYYY-MM-DD', verbose_name='زمان انتشار'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', ckeditor.fields.RichTextField(help_text='نظر خود را بنویسید', verbose_name='نظر')),
                ('active', models.BooleanField(default=False)),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='فرمت صحیح تاریخ YYYY-MM-DD', verbose_name='زمان انتشار')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل کاربر')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
