# Generated by Django 4.2.2 on 2023-08-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_options_remove_article_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_like', to='blog.article', verbose_name='مقاله'),
        ),
    ]
