# Generated by Django 4.2.2 on 2023-08-12 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_remove_comment_likes_article_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='likes_comment', to=settings.AUTH_USER_MODEL, verbose_name='لایک'),
        ),
    ]
