# Generated by Django 4.2.2 on 2023-06-29 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='product')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('unit_price', models.PositiveIntegerField(default=0)),
                ('information', models.TextField(blank=True, null=True)),
                ('discount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
