# Generated by Django 4.2.2 on 2023-07-01 08:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_color_size_product_status_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(default='#fff', image_field=None, max_length=18, samples=None),
        ),
    ]
