# Generated by Django 4.2.2 on 2023-07-01 10:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_color_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='information',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
