# Generated by Django 4.2.2 on 2023-07-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_brand_product_color_product_size_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_favourite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
