# Generated by Django 4.2.2 on 2023-07-13 14:08

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_product_sell_product_total_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell',
            field=models.PositiveIntegerField(default=0, verbose_name='پر فروش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_favourite',
            field=models.PositiveIntegerField(default=0, verbose_name='مجموع محبوب ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.PositiveIntegerField(default=0)),
                ('update', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('prodcut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_update', to='home.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_update', to='home.variants')),
            ],
            options={
                'verbose_name': 'چارت محصول',
                'verbose_name_plural': 'چارت محصولات',
            },
        ),
    ]
