# Generated by Django 4.2.2 on 2023-07-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_product_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='change',
            field=models.BooleanField(default=True),
        ),
    ]
