# Generated by Django 4.2.2 on 2023-07-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_variants_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='prodcut',
            new_name='product',
        ),
    ]
