# Generated by Django 4.2.2 on 2023-07-16 07:45

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_prodcut_chart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='change',
            field=models.BooleanField(default=True, verbose_name='عوض کردن'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان بروزرسانی محصول'),
        ),
    ]
