# Generated by Django 4.2.2 on 2023-07-16 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0025_product_num_view_product_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='product_view', to=settings.AUTH_USER_MODEL),
        ),
    ]
