# Generated by Django 4.2.2 on 2023-07-16 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها '},
        ),
        migrations.AlterField(
            model_name='chart',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ محصول'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_update', to='home.product', verbose_name='انتخاب محصول'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سایز محصول'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت محصول'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_update', to='home.variants', verbose_name='انتخاب گونه محصول'),
        ),
        migrations.AlterField(
            model_name='views',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان بازدید'),
        ),
        migrations.AlterField(
            model_name='views',
            name='ip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس آی پی کاربر'),
        ),
        migrations.AlterField(
            model_name='views',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product', verbose_name='بازدید محصول'),
        ),
    ]
