# Generated by Django 4.2.2 on 2023-07-16 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0028_alter_category_options_alter_chart_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='views',
            options={'verbose_name': 'بازدید محصول', 'verbose_name_plural': 'بازدید های محصولات'},
        ),
        migrations.AlterField(
            model_name='product',
            name='change',
            field=models.BooleanField(default=True, verbose_name='عوض کردن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='home.color', verbose_name='رنگ محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_view',
            field=models.PositiveIntegerField(default=0, verbose_name='مجموع بازدید ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='home.size', verbose_name='سایز محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='product_view', to=settings.AUTH_USER_MODEL, verbose_name='بازدید ها'),
        ),
    ]
