# Generated by Django 4.2.2 on 2023-07-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_views_options_alter_product_change_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام اسلایدر')),
                ('image', models.ImageField(blank=True, upload_to='gallery/', verbose_name='عکس اسلایدر')),
            ],
            options={
                'verbose_name': 'عکس اسلایدر',
                'verbose_name_plural': 'عکس های اسلایدر',
            },
        ),
    ]
