# Generated by Django 4.2.2 on 2023-07-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='sale_off',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='نخفیف محصول'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='sale_session',
            field=models.CharField(blank=True, choices=[('بهار', 'بهار'), ('تابستان', 'تابستان'), ('پاییز', 'پاییز'), ('زمستان', 'زمستان')], max_length=10, verbose_name='فروش فصلی'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متن اسلایدر'),
        ),
    ]
