# Generated by Django 4.2.2 on 2023-07-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('None', 'none'), ('Size', 'size'), ('Color', 'color'), ('Both', 'Both')], max_length=200, null=True, verbose_name='وضعیت گونه محصول'),
        ),
    ]
