# Generated by Django 4.2.2 on 2023-08-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_product_img_1_product_img_2_product_img_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_4',
        ),
    ]
