# Generated by Django 4.2.2 on 2023-08-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_comment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
