# Generated by Django 4.2.2 on 2023-07-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_variant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compare',
        ),
    ]
