# Generated by Django 4.2.2 on 2023-07-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorder',
            name='product',
        ),
        migrations.AddField(
            model_name='itemorder',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='قیمت'),
        ),
    ]
